name: Update Pinned Repos
on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Pinned Repos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update Pinned Repositories
        uses: matchai/pin-repo@v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}