name: Update Pinned Repos

on:
  schedule:
    # 每 8 小时运行一次
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Pinned Repositories
        uses: artiebits/auto-readme-pinned-repos@v2.2.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}