name: Update Activity Feed

on:
  schedule:
    # 每小时运行一次
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-activity:
    name: Update README with recent activity
    runs-on: ubuntu-latest

    # 关键修正：在这里增加 permissions 块，授予工作流写入内容的权限
    permissions:
      contents: write 

    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://github.com/Eric-Terminal.atom"
          readme_path: './README.md'
          committer_username: 'github-actions[bot]'
          committer_email: 'github-actions[bot]@users.noreply.github.com'
          comment_tag_name: "activity"
          max_post_count: 5
          template: "> $title$ - `($date$)`"